name: cli-options-args
version: 0.0.1.0
ghc-options: 
  -Wall 
  -Werror 
  -Wno-unused-matches 
  -Wincomplete-uni-patterns 
  -Wincomplete-record-updates 
  -Wmissing-import-lists

dependencies: 
  - base
  - optparse-applicative
  - HUnit
library:
  source-dirs: src
  exposed-modules: 
    - Lib

tests:
  options-test:
    source-dirs: test
    main: Test.hs
    dependencies: 
      - HUnit
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: cli-options-args

executables:
  cli-options-args:
    source-dirs: app
    main: Main.hs 
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: cli-options-args


